# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

schedule:

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 1825
  exclude:
    domains:
      - automation
      - media_player
    entities:
      - light.table_de_chevet_de_yan
      - light.table_de_chevet_de_cath

device_tracker:
  - platform: google_maps
    username: !secret tracker_account
    max_gps_accuracy: 100

google_assistant:
  project_id: !secret project_id
  service_account: !include service_account.json
  report_state: true
  expose_by_default: false
  entity_config:
    switch.front_yard:
      expose: true
      name: Extérieur
      aliases:
        - Devant
        - Avant
    light.master_bathroom_ceiling:
      expose: true
      name: Salle de bain
      aliases:
        - Plafond de la salle de bain
    light.master_bathroom_mirror:
      expose: true
      name: Miroir de la salle de bain
    switch.master_bathroom_fan:
      expose: true
      name: Fan de la salle de bain
      aliases:
        - Fan
    light.kitchen:
      expose: true
      name: Cuisine
    light.living_room:
      expose: true
      name: Salon
    #light.twinkly_a80df9:
    #  expose: true
    #  name: Sapin
    light.upper_stairs:
      expose: true
      name: Escalier
    light.ground_floor_hallway:
      expose: true
      name: corridor
    cover.kitchen_window_blind:
      expose: true
      name: Fenêtre de la cuisine
    cover.patio_door_blind:
      expose: true
      name: Fenêtre du patio
    cover.living_room_window_blind:
      expose: true
      name: Fenêtre du salon
    cover.office_window_blind:
      expose: true
      name: Fenêtre du bureau
    climate.main_floor:
      expose: true
      name: Thermostat

tts:
  - platform: google_translate

notify:
  - name: all_people
    platform: group
    services:
      - service: yan
      - service: cath
  - name: yan
    platform: group
    services:
      - service: pushover
        data:
          target: pixel7
  - name: cath
    platform: group
    services:
      - service: pushover
        data:
          target: cath

shell_command:
  set_garage_camera_time: !secret camera_garage_set_time_template
  set_rear_window_camera_time: !secret camera_rear_window_set_time_template
  set_parking_camera_time: !secret camera_parking_set_time_template

hyperion_priority:
  host: !secret hyperion_ip_address
  port: !secret hyperion_port

rest_command:
  garage_camera_output:
    url: !secret camera_garage_output_url
    username: !secret camera_garage_username
    password: !secret camera_garage_password
  frigate_set_reviewed:
    url: !secret frigate_reviewed_url
    method: POST
    content_type: "application/json; charset=utf-8"
    payload: '{"ids":["{{ id }}"]}'

automation: !include_dir_merge_list automation
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_button: !include input_button.yaml
input_select: !include input_select.yaml
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
template: !include_dir_merge_list template
command_line: !include_dir_merge_list command_line
scene: !include scenes.yaml

mqtt:
  sensor: !include_dir_merge_list mqtt/sensor
  switch: !include_dir_merge_list mqtt/switch
  binary_sensor: !include_dir_merge_list mqtt/binary_sensor
  alarm_control_panel: !include_dir_merge_list mqtt/alarm_control_panel
