---
- platform: template
  switches:
    nintendo:
      value_template: "{{ is_state('select.yharmony_activities', 'Nintendo') }}"
      turn_on:
        action: select.select_option
        data:
          entity_id: select.yharmony_activities
          option: "Nintendo"
      turn_off:
        action: select.select_option
        data:
          entity_id: select.yharmony_activities
          option: "power_off"
