---
- alias: Notify when ender3 print is done
  id: Notify_when_ender3_print_is_done
  triggers:
    trigger: state
    entity_id: binary_sensor.octoprint_printing
    from: "on"
    to: "off"
  actions:
    - action: script.notify_and_speak
      data:
        message: L'impression 3D est terminée.
