---
- alias: Washer leak detected
  id: Washer_leak_detected
  triggers:
    - trigger: state
      entity_id: binary_sensor.washer_leak_sensor
      to: "on"
  actions:
    - action: switch.turn_off
      entity_id: switch.washer_power
    - action: hyperion_priority.apply_effect
      data:
        effect: Knight rider
        priority: 100
    - action: notify.tv
      data:
        message: "Washing machine is leaking"
    - repeat:
        sequence:
          - action: notify.all_people
            data:
              message: "De l'eau est détectée dans le bac de la laveuse."
          - delay:
              seconds: 10
        until:
          - condition: state
            entity_id: binary_sensor.washer_leak_sensor
            state: "off"
    - action: notify.all_people
      data:
        message: Le problème est maintenant réglé.
    - action: hyperion_priority.clear_priority
      data:
        priority: 100
