---
- alias: Alert when house heating is out of normal parameters
  id: Alert_when_house_heating_is_out_of_normal_parameters
  triggers:
    trigger: state
    entity_id: climate.main_floor
  variables:
    climate_mode: "{{ states('climate.main_floor') }}"
    single_temp_target: >-
      {{ state_attr('climate.main_floor', 'temperature')|float(0) }}
    high_temp_target: >-
      {{ state_attr('climate.main_floor', 'target_temp_high')|float(0) }}
    low_temp_target: >-
      {{ state_attr('climate.main_floor', 'target_temp_low')|float(0) }}
  conditions:
    # if the climate was manually set.
    - >-
      {{ is_state_attr('climate.main_floor', 'preset_mode', 'temp')
          or climate_mode == 'off' }}
    - or:
        - "{{ climate_mode == 'heat' and single_temp_target > 23 }}"
        - "{{ climate_mode == 'heat' and single_temp_target < 20  }}"
        - "{{ climate_mode == 'cool' and single_temp_target < 21  }}"
        - "{{ climate_mode == 'cool' and single_temp_target > 26  }}"
        - "{{ climate_mode == 'heat_cool' and low_temp_target > 23  }}"
        - "{{ climate_mode == 'heat_cool' and low_temp_target < 19  }}"
        - "{{ climate_mode == 'heat_cool' and high_temp_target < 20  }}"
        - "{{ climate_mode == 'heat_cool' and high_temp_target > 26  }}"
        - >-
          {{ single_temp_target == high_temp_target == low_temp_target == 0 }}
  actions:
    - action: ecobee.resume_program
      data:
        entity_id: climate.main_floor
        resume_all: true
    - action: notify.all_people
      data:
        message: >-
          Le thermostat de la maison a été
          configuré en dehors des paramètres normaux.
          mode: {{ climate_mode }}
          {% if climate_mode == "heat_cool" %}
          Température minimale: {{ low_temp_target }}
          Température maximale: {{ high_temp_target }}
          {% else %}
          Température cible: {{ single_temp_target }}
          {% endif %}

- alias: Alert for food
  id: alert_for_food
  triggers:
    trigger: time
    at: "12:45:00"
  actions:
    - action: media_player.volume_set
      entity_id: media_player.kitchen
      data:
        volume_level: 0.2
    - action: tts.google_translate_say
      entity_id: media_player.kitchen
      data:
        message: N'oubliez pas de ranger la nourriture sur le comptoir.
        language: "fr"

- alias: Home assistant started notification
  triggers:
    trigger: homeassistant
    event: start
  actions:
    - action: media_player.volume_set
      entity_id: media_player.maison
      data:
        volume_level: 0.2
    - action: tts.google_translate_say
      entity_id: media_player.kitchen
      data:
        message: Home Assistant est démarré.
        language: "fr"
    - action: notify.yan
      data:
        message: "Home Assistant started."

- alias: Alert midnight resets
  triggers:
    - trigger: time
      at: "00:00:00"
  actions:
    - action: input_boolean.turn_off
      entity_id: input_boolean.yan_had_pills

- alias: yan pills notify
  id: yan_pills_notify
  triggers:
    - trigger: time
      at: "21:00:00"
    - trigger: state
      entity_id: input_boolean.yan_phone_plugged
      to: "on"
  conditions:
    - condition: state
      entity_id: input_boolean.yan_had_pills
      state: "off"
    - condition: state
      entity_id: input_boolean.yan_phone_plugged
      state: "on"
    - condition: time
      after: "21:00:00"
      before: "04:00:00"
  mode: single
  actions:
    - action: notify.yan
      data:
        message: "Yan, prends tes pillules!"
    - and:
        - condition: state
          entity_id: person.yan
          state: "home"
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: "disarmed"
    - repeat:
        sequence:
          - delay: "00:00:02"
          - action: light.turn_on
            data:
              entity_id: light.table_de_chevet_de_yan
              brightness: 56
              xy_color: [0.672, 0.324]
              transition: 1
          - delay: "00:00:02"
          - action: light.turn_off
            data:
              entity_id: light.table_de_chevet_de_yan
              transition: 1
        until: '{{ is_state("input_boolean.yan_had_pills", "on") }}'
    - action: light.turn_on
      data:
        entity_id: light.table_de_chevet_de_yan
        brightness: 1
        color_temp_kelvin: 2732
    - action: light.turn_off
      entity_id: light.table_de_chevet_de_yan

- alias: Notify when device has low battery
  triggers:
    trigger: numeric_state
    entity_id:
      - sensor.fridge_door_battery_level
      - sensor.front_door_lock_battery_level
      - sensor.garage_door_lock_battery_level
      - sensor.washer_leak_sensor_battery
    below: 10
  mode: parallel
  actions:
    - repeat:
        count: 4
        sequence:
          - action: notify.yan
            data:
              message: >
                La batterie {{ trigger.entity_id }} doit être changée.
          - delay: "01:00:00"
