---
- alias: Halloween spooky lights
  triggers:
    trigger: state
    entity_id: input_boolean.halloween
    to: "on"
  mode: parallel
  actions:
    - repeat:
        sequence:
          - action: switch.turn_off
            entity_id: switch.front_yard
          - delay:
              milliseconds: "{{ ( range(100, 700) | random | int) }}"
          - action: switch.turn_on
            entity_id: switch.front_yard
          - delay:
              milliseconds: "{{ ( range(2000, 4000) | random | int) }}"
        until:
          - condition: state
            entity_id: input_boolean.halloween
            state: "off"
