---
- alias: sync photo yan
  id: sync_photo_yan
  triggers:
    - trigger: state
      entity_id: input_button.sync_photo_yan
  actions:
    - action: joaoapps_join.android_server_send_tasker
      data:
        command: "SyncPhotoYan"
