---
- alias: Cath leaving home
  id: cath_leaving_home
  triggers:
    - trigger: zone
      entity_id: person.cath
      zone: zone.home
      event: leave
  conditions:
    - condition: time
      before: "10:00:00"
  actions:
    action: light.turn_off
    entity_id: all

- alias: Yan leaving work
  triggers:
    trigger: zone
    entity_id: person.yan
    zone: zone.work_yan
    event: leave
  conditions:
    - condition: time
      after: !secret yan_leave_work_time
      before: "23:00:00"
  actions:
    action: notify.cath
    data:
      message: >
        Yan est parti du travail. Il faut
        {{ states('sensor.yantohome') }} minutes pour rentrer à la maison.

- alias: Cath leaving work
  triggers:
    - trigger: zone
      entity_id: person.cath
      zone: zone.work_cath
      event: leave
  actions:
    action: notify.yan
    data:
      message: >
        Cath est parti du travail. Il faut
        {{ states('sensor.cathtohome') }} minutes pour rentrer à la maison.
