---
- alias: Frederique main light brightness
  triggers:
    - trigger: state
      entity_id: light.frederique_bedroom
      attribute: brightness
  mode: restart
  actions:
    repeat:
      sequence:
        - action: light.turn_on
          data:
            entity_id: light.frederique_night_light
            brightness: >-
              {{ state_attr('light.frederique_bedroom', 'brightness')
                |int(0) }}
        - delay:
            milliseconds: 500
      until: >-
        {{ (state_attr('light.frederique_night_light', 'brightness')|int(0))
          ==
          (state_attr('light.frederique_bedroom', 'brightness')|int(0)) }}

- alias: Frederique main light triple up
  triggers:
    - trigger: state
      entity_id: event.frederique_bedroom_scene_001
      attribute: event_type
      to: "KeyPressed3x"
  actions:
    - action: light.turn_on
      data:
        entity_id: light.frederique_night_light
        brightness: 255

- alias: Frederique main light triple down
  triggers:
    - trigger: state
      entity_id: event.frederique_bedroom_scene_002
      attribute: event_type
      to: "KeyPressed3x"
  actions:
    - action: light.turn_off
      data:
        entity_id:
          - light.frederique_night_light
          - light.frederique_bedroom

- alias: Stairs double down
  triggers:
    - trigger: state
      entity_id: event.upper_stairs_scene_002
      attribute: event_type
      to: "KeyPressed2x"
    - trigger: state
      entity_id: event.ground_floor_hallway_scene_002
      attribute: event_type
      to: "KeyPressed2x"
  actions:
    - action: light.turn_on
      data:
        entity_id:
          - light.table_de_chevet_de_cath
          - light.table_de_chevet_de_yan
        brightness: 150

- alias: Kitchen double up/down
  id: kitchen_double_up_down
  triggers:
    - trigger: state
      entity_id: event.kitchen_scene_001
      attribute: event_type
      to: "KeyPressed2x"
    - trigger: state
      entity_id: event.kitchen_scene_002
      attribute: event_type
      to: "KeyPressed2x"
  actions:
    - action: >
        light.turn_{{ "on" if trigger.entity_id.endswith("001")
                      else "off"}}
      entity_id:
        - light.kitchen
        - light.living_room
        - light.ground_floor_hallway
        - light.reading_room

- alias: Frederique main light double down
  triggers:
    - trigger: state
      entity_id: event.frederique_bedroom_scene_002
      attribute: event_type
      to: "KeyPressed2x"
  actions:
    - action: light.turn_off
      data:
        entity_id: light.frederique_bedroom
    - action: switch.turn_on
      data:
        entity_id: switch.baby_monitor
    - action: script.turn_on
      data:
        entity_id: script.white_noise_stop
        variables:
          media_player_id: media_player.bureau
    - action: script.turn_on
      data:
        entity_id: script.white_noise_start
        variables:
          media_player_id: media_player.bureau

- alias: Frederique main light single up or release from hold up
  triggers:
    - trigger: state
      entity_id: event.frederique_bedroom_scene_001
      attribute: event_type
      to: "KeyPressed"
    - trigger: state
      entity_id: event.frederique_bedroom_scene_001
      attribute: event_type
      to: "KeyHeldDown"
  mode: single
  max_exceeded: silent
  actions:
    - action: switch.turn_off
      data:
        entity_id: switch.baby_monitor
    - action: script.turn_on
      data:
        entity_id: script.white_noise_stop
        variables:
          media_player_id: media_player.bureau

- alias: Set zwave light to default when single click up
  id: Set_zwave_light_to_default_when_single_click_up
  triggers:
    - trigger: event
      event_type: zwave_js_value_notification
      event_data:
        value: "KeyPressed"
        property_key_name: "001"
  variables:
    light_entity_id: >-
      {{ device_entities(trigger.event.data.device_id)|select('match', 'light\\.')|first }}
  condition: >-
    {{ states(light_entity_id) != "unknown" and
      light_entity_id not in states.group.zwave_dimmers_default_exclude.attributes.entity_id }}
  actions:
    - action: light.turn_on
      data:
        entity_id: "{{ light_entity_id }}"
        brightness: >-
          {% if light_entity_id in
                states.group.zwave_dimmers_default_low.attributes.entity_id %}
            1
          {% else %}
            255
          {% endif %}
    - action: zwave_js.refresh_value
      data:
        entity_id: "{{ light_entity_id }}"

- alias: Bathroom ceiling light single click up
  triggers:
    - trigger: state
      entity_id: event.master_bathroom_ceiling_scene_001
      attribute: event_type
      to: "KeyPressed"
  actions:
    - action: light.turn_on
      data:
        entity_id:
          - light.master_bathroom_ceiling
          - light.master_bathroom_mirror
        brightness: 255
    - action: switch.turn_on
      data:
        entity_id: switch.master_bathroom_fan

- alias: bathroom any light single click down
  triggers:
    - trigger: state
      entity_id: event.master_bathroom_ceiling_scene_002
      attribute: event_type
      to: "KeyPressed"
    - trigger: state
      entity_id: event.master_bathroom_mirror_scene_002
      attribute: event_type
      to: "KeyPressed"
  actions:
    - action: light.turn_off
      entity_id:
        - light.master_bathroom_ceiling
        - light.master_bathroom_mirror
    - action: script.auto_off
      data:
        auto_entity: switch.master_bathroom_fan
        duration_seconds: 1800

- alias: bathroom fan double click up
  triggers:
    - trigger: state
      entity_id: event.master_bathroom_fan_scene_001
      attribute: event_type
      to: "KeyPressed2x"
  actions:
    - action: script.auto_switch_on
      data:
        auto_entity: switch.master_bathroom_fan
        duration_seconds: 1800

- alias: bathroom fan triple click up
  triggers:
    - trigger: state
      entity_id: event.master_bathroom_fan_scene_001
      attribute: event_type
      to: "KeyPressed3x"
  actions:
    - action: script.auto_switch_on
      data:
        auto_entity: switch.master_bathroom_fan
        duration_seconds: 3600

- alias: bathroom any light double click up
  triggers:
    - trigger: state
      entity_id: event.master_bathroom_ceiling_scene_001
      attribute: event_type
      to: "KeyPressed2x"
    - trigger: state
      entity_id: event.master_bathroom_mirror_scene_001
      attribute: event_type
      to: "KeyPressed2x"
  variables:
    light_entity_id: >-
      {{ device_entities(device_id(trigger.entity_id))|select('match', 'light\\.')|first | first }}
  condition: '{{ states(light_entity_id) != "unknown" }}'
  actions:
    - action: light.turn_on
      data:
        entity_id: "{{ light_entity_id }}"
        brightness: 255

- alias: bathroom ceiling triple click up
  id: bathroom_ceiling_triple_click_up
  triggers:
    - trigger: state
      entity_id: event.master_bathroom_ceiling_scene_001
      attribute: event_type
      to: "KeyPressed3x"
  actions:
    - action: light.turn_on
      data:
        entity_id: light.master_bathroom_ceiling
        brightness: 255
    - action: switch.turn_on
      entity_id: switch.heated_bed

- alias: Heated bed turn off after 20 minutes
  id: Heated_bed_turn_off_after_20_minutes
  triggers:
    - trigger: state
      entity_id: switch.heated_bed
      to: "on"
      for:
        minutes: 20
  actions:
    - action: switch.turn_off
      entity_id: switch.heated_bed

- alias: bathroom ceiling tripple click down
  triggers:
    - trigger: state
      entity_id: event.master_bathroom_ceiling_scene_002
      attribute: event_type
      to: "KeyPressed3x"
  actions:
    - action: light.turn_off
      entity_id:
        - light.master_bathroom_ceiling
        - light.master_bathroom_mirror
    - action: switch.turn_off
      entity_id: switch.master_bathroom_fan
    - action: light.turn_on
      data:
        entity_id:
          - light.kitchen
          - light.upper_stairs
        brightness: 40

- alias: bathroom any light double click down
  id: bathroom_any_light_double_click_down
  triggers:
    - trigger: state
      entity_id: event.master_bathroom_ceiling_scene_002
      attribute: event_type
      to: "KeyPressed2x"
    - trigger: state
      entity_id: event.master_bathroom_mirror_scene_002
      attribute: event_type
      to: "KeyPressed2x"
  variables:
    light_entity_id: >-
      {{ device_entities(device_id(trigger.entity_id))|select('match', 'light\\.')|first | first }}
  condition: '{{ states(light_entity_id) != "unknown" }}'
  actions:
    - action: light.turn_off
      data:
        entity_id: "{{ light_entity_id }}"

- alias: front light double click down
  triggers:
    - trigger: state
      entity_id: event.front_yard_scene_002
      attribute: event_type
      to: "KeyPressed2x"
  actions:
    - action: light.turn_off
      entity_id:
        - light.kitchen
        - light.upper_stairs

- alias: Fred bathroom main light single click up
  id: fred_bathroom_main_light_single_click_up
  triggers:
    - trigger: state
      entity_id: event.frederique_bathroom_scene_001
      attribute: event_type
      to: "KeyPressed"
  mode: single
  max_exceeded: silent
  variables:
    brightness: >
      {{ 103 if (19 <= now().hour or now().hour < 7) and
         is_state('switch.baby_monitor', 'on') else 255 }}
  actions:
    - action: light.turn_on
      data:
        entity_id: light.frederique_bathroom
        brightness: "{{ brightness }}"
    - condition: "{{ brightness == 103 }}"
    - delay: "00:10:00"
    - action: light.turn_off
      data:
        entity_id: light.frederique_bathroom
