---
- alias: Sync backyard camera time
  id: sync_backyard_camera_time
  triggers:
    - trigger: time
      at: "00:00:00"
    - trigger: homeassistant
      event: start
  actions:
    - action: shell_command.set_rear_window_camera_time