---
- alias: Sync backyard camera time
  id: sync_backyard_camera_time
  triggers:
    - trigger: time
      at: "00:00:00"
    - trigger: homeassistant
      event: start
  conditions:
    condition: state
    entity_id: camera.backyard
    state: idle
  actions:
    - action: shell_command.set_rear_window_camera_time

- alias: Notify when motion in backyard
  id: Notify_when_motion_in_backyard
  mode: single
  max_exceeded: silent
  triggers:
    - trigger: state
      entity_id: binary_sensor.backyard_motion_detection
      to: "on"
  conditions:
    - condition: template
      value_template: >
        {{ (as_timestamp(now()) -
            as_timestamp(states.cover.living_room_window_blind.last_changed))
          > 20 }}
  actions:
    - action: camera.snapshot
      data:
        entity_id: camera.backyard
        filename: /media/backyard.jpg
    - action: notify.yan
      data:
        message: "Backyard Motion detected"
        data:
          attachment: /media/backyard.jpg
    - delay: "00:05:00"
