---
- alias: Sync front window camera time
  id: sync_front_window_camera_time
  triggers:
    - trigger: time
      at: "00:00:00"
    - trigger: homeassistant
      event: start
  conditions:
    condition: state
    entity_id: camera.front_window
    state: idle
  actions:
    - action: shell_command.set_front_window_camera_time
