---
- alias: Sync garage camera time
  id: sync_garage_camera_time
  triggers:
    - trigger: time
      at: "00:00:00"
    - trigger: homeassistant
      event: start
  actions:
    - action: shell_command.set_garage_camera_time

- alias: Garage door button pushed
  id: Garage_door_button_pushed
  mode: single
  max_exceeded: silent
  triggers:
    - trigger: state
      entity_id: input_button.garage_door
  actions:
    - action: rest_command.garage_camera_output
