---
- alias: Sync parking camera time
  id: sync_parking_camera_time
  triggers:
    - trigger: time
      at: "00:00:00"
    - trigger: homeassistant
      event: start
  actions:
    - action: shell_command.set_parking_camera_time
